### ISSUE TITLE
Erroneous tracking of open files

### ISSUE THREAD

**Issue by johnzeringue** [sugarlabs/Pippy#29]
Related to #27, because an example will take the place of an unmodified tab, it's possible to receive an error claiming that the selected file is already open. However, the file is in no way visible to the user.

Steps to reproduce:
1. Open Pippy.
2. In a new tab, write some text. For example:
   
   ```
   print 'Hello, world!'
   ```
3. Rename the tab to `Hello`.
4. Export as Pippy document.
5. Open a new tab.
6. Close the `Hello` tab.
7. Import Python file to new tab selecting `Hello.py`.
8. Load an example. The example should replace `Hello`.
9. Import Python file to new tab selecting `Hello.py`.
10. You should now see the following error message:
    
    ```
    Error importing Python file
    The file you selected is already open
    ```
    
    The example should remain in its tab. `Hello` should not be visible.

I think that the solution here is to always open files in new tabs. The only exception might be a _blank_, unmodified tab. @walterbender, I'd be glad to try implement this in a pull request. However, could you weight in before I go off and do this?

**Comment by walterbender** [comment]
775ef6ecb9c1fe86c6311eea1846624d4c4d34c4 should have fixed this issue. Please reopen if the problem persists.
