### ISSUE TITLE
LICENSE is GPLv3+, COPYING is GPLv2+, included box2d is GPLv3+, activity.info is GPLv2+

### ISSUE THREAD

**Issue by quozl** [sugarlabs/Pippy#54]
Conflicting license claims in source.

**Comment by cosmicAsymmetry** [comment]
Conflicting with Pippy licence in https://github.com/sugarlabs/develop-activity
What is to be done in cases like this, where an older version of code is carrying v2.0, would we need to licence Develop under v2.0 or can we licence it under v3.0? I'm not sure, but to me the former makes more sense.

**Comment by quozl** [comment]
Thanks.

Moving Pippy to GPLv3+ seems possible, as "or later" is used.  An edit of source files here.

Then, use the new Pippy source files in Develop.

Then, moving Develop to GPLv3+ is not blocked by the Pippy source files, and the next blockage if any will be revealed.

**Comment by quozl** [comment]
7698d003e28c0817c41f1b6c1ca7e25d3709e512
