### ISSUE TITLE
PyGameActivity not yet ported to GTK+ 3

### ISSUE THREAD

**Issue by quozl** [sugarlabs/Pippy#55]
Activity wrapper for PyGame has not been ported;

- [ ] it does not instantiate the ToolbarBox,
- [ ] it tries to run the generated activity as a forked process with two Xcb connections, causing this error;

```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.

```

**Comment by quozl** [comment]
https://github.com/sugarlabs/Snow/commit/8cf63f6976bd1cfbc583ced8e96de2cabb1a9db2 is related.

**Comment by yashagrawal3** [comment]
@quozl How to reproduce error in the second task?

**Comment by quozl** [comment]
Use Pippy to write a PyGame program, then export as activity, then run it?

My guess, not verified because otherwise I would have fixed it ... is that the Snow activity was exported using Pippy from the graphics example;

* https://github.com/sugarlabs/Pippy/blob/master/data/en/graphics/snow
* https://github.com/sugarlabs/Snow

And since I had to fix Snow, and the code looked very much like Pippy at a point in history long past, and the code in Pippy hasn't changed fully, the problem is still there.

**Comment by yashagrawal3** [comment]
I tried a lot of things but still unable to reproduce error in second task. I have made changes in activity.py with the help of https://github.com/sugarlabs/Snow/commit/8cf63f6976bd1cfbc583ced8e96de2cabb1a9db2 though.

**Comment by quozl** [comment]
Good, thanks for testing.  It must have been fixed between when Snow was exported and now.

**Comment by yashagrawal3** [comment]
Do you want me to create a PR with similar changes as in 
https://github.com/sugarlabs/Snow/commit/8cf63f6976bd1cfbc583ced8e96de2cabb1a9db2 ?

**Comment by quozl** [comment]
Are they necessary with the current Pippy?

**Comment by yashagrawal3** [comment]
No effect on any functionality, but ported pygameActivity to Gtk+3. As I said very similar to above mentioned PR in snow.

**Comment by quozl** [comment]
Sorry, I still don't know if Pippy needs what you've done; perhaps you could make a pull request so I can see? :grin:
