### ISSUE TITLE
Feature request: Indent in next line following ':'

### ISSUE THREAD

**Issue by sanjaymaniam** [sugarlabs/Pippy#74]
':' followed by enter should give me in an indent in the next line.

```
for i in range(10):
(~tab here~) print ('foo')
```

**Comment by quozl** [comment]
As a teaching tool, I don't think Pippy should do this.  Develop may have this feature.

**Comment by sparshg** [comment]
Agreed, should we close this and #73?

**Comment by chimosky** [comment]
> As a teaching tool, I don't think Pippy should do this. Develop may have this feature.

Agreed, closing this.
